### PR TITLE
Finished every test case

### PR DESCRIPTION
**Pull request by edlingao**

### CODE REVIEW

**Review by inhaq — CHANGES_REQUESTED** [review]
Great work, but two tests are missing in this project i.e. `my_count` and `my_inject`. Usually, unit testing is good to be done for all pure functions.
Once updated, kindly resubmit for review.

**Comment by edlingao** [comment]
Screen Shot 2019-05-15 at 17 57 03

**Comment by edlingao** [comment]
Sorry i thought i only got to test 6 of them

**Comment by inhaq** [comment]
Ah Sorry, my bad. You're right. But IMO, writing tests for all functions will be a good practice as it'll be also helpful in rails sections. Thanks for reminding the info 😊

**Comment by edlingao** [comment]
Don't worry i added it, thanks for the advise 😄

**Review by inhaq — APPROVED** [review]
Great job. It's 👍🏻
Good luck with the next project 😊

**Pull request merged**
